# PyInstaller spec for the Windows desktop build.
#
#   .venv\Scripts\pyinstaller.exe desktop\build.spec --noconfirm
#
# Produces dist\ChakwalDCChakwal\ChakwalDC.exe -- one folder, one .exe to
# double-click. Not onefile on purpose: a onefile build unpacks ~40 MB to a
# temp folder on every launch, which makes the app feel slow to start, and the
# 6 MB of reference data would be re-extracted each time as well.
#
# What has to be declared explicitly, and why:
#   pathex        main.py imports `app` and `govapi` from the project root at
#                 runtime via sys.path, so the static analyser cannot see them.
#   hiddenimports uvicorn picks its event loop, HTTP protocol and lifespan
#                 implementation at runtime by name. Nothing imports them, so
#                 without this the frozen app starts and then serves nothing.
#   datas         the web folder: the page, the scripts, and the 226 per-mouza
#                 Khasra files that make the parcel lists work offline.

import os

PROJ = os.path.abspath(os.path.join(SPECPATH, ".."))
WEB = os.path.join(PROJ, "desktop", "web")
# The app's icon, generated by desktop\installer\make-icon.ps1. Optional: a
# missing icon must not fail the build, it just means the generic PyInstaller
# one gets embedded.
ICON = os.path.join(PROJ, "desktop", "installer", "chakwal.ico")
ICON = ICON if os.path.isfile(ICON) else None

a = Analysis(
    [os.path.join(PROJ, "desktop", "main.py")],
    pathex=[PROJ],
    binaries=[],
    datas=[(WEB, "web")],
    hiddenimports=[
        "app",
        "govapi",
        "uvicorn.logging",
        "uvicorn.loops.auto",
        "uvicorn.loops.asyncio",
        "uvicorn.protocols.http.auto",
        "uvicorn.protocols.http.h11_impl",
        "uvicorn.protocols.websockets.auto",
        "uvicorn.lifespan.on",
        "uvicorn.lifespan.off",
        "webview",
        "webview.platforms.edgechromium",
    ],
    hookspath=[],
    runtime_hooks=[],
    excludes=[
        # Not used by this app, and both are large. Dropping them keeps the
        # folder small enough to sit on a desktop without complaint.
        "tkinter",
        "matplotlib",
        "numpy",
        "pandas",
        "pytest",
    ],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="ChakwalDC",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    # No console: this is a window, not a terminal. Errors are written to
    # desktop-error.log in the state folder instead (see main.py).
    console=False,
    disable_windowed_traceback=False,
    icon=ICON,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name="ChakwalDC",
)
